pipeline {
  agent {
    node {
      label 'runner'
    }

  }
  stages {
    stage('Build miniconda-cuda') {
      steps {
        build(wait: true, propagate: true, job: 'gpuci/gpuci-build-environment/miniconda-cuda')
      }
    }

  }
}